name: ai-cluster

services:

  ai-1:
    build: ./
    container_name: ai-1
    ports:
      - "8086:8086"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      start_period: 15s
      interval: 5s
      timeout: 15s
      retries: 10
    volumes:
      - ai-vector-data:/app/data
    environment:
      - SPRING_AI_VECTORSTORE_PATH=/app/data/vectorstore.json
      - SPRING_AI_OPENAI_API_KEY=AIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - SPRING_AI_OPENAI_EMBEDDING_API_KEY=AIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - REPLICA_ID=1
      - SERVER_PORT=8086
    networks:
      - nexus-dev

  ai-2:
    build: ./
    container_name: ai-2
    ports:
      - "8087:8087"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1" ]
      start_period: 15s
      interval: 5s
      timeout: 15s
      retries: 10
    volumes:
      - ai-vector-data:/app/data
    environment:
      - SPRING_AI_VECTORSTORE_PATH=/app/data/vectorstore.json
      - SPRING_AI_OPENAI_API_KEY=AIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - SPRING_AI_OPENAI_EMBEDDING_API_KEY=AIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - REPLICA_ID=2
      - SERVER_PORT=8087
    networks:
      - nexus-dev

volumes:
  ai-vector-data:

networks:
  nexus-dev:
    external: true