spring:
  application:
    name: AI
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
        max-attempts: 6
  ai:
    mcp:
      client:
        sse:
          connections:
            nexus-mpc:
              url: http://gateway/nexus

  profiles:
    active: dev

management:
  endpoint:
    configprops:
      access: unrestricted
      show-values: always
    env:
      access: unrestricted
      show-values: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ai-${REPLICA_ID:1}
    hostname: ai-${REPLICA_ID:1}
    app-group-name: ai